- hosts: web
  remote_user: ubuntu
  become: yes
  vars:
    apache_vhosts:
        documentroot: "/var/www/wordpress"
  roles:
    - apache
    - php
    - apache-php-fpm

- hosts: db
  remote_user: ubuntu
  become: yes
  vars_files:
     - vars/Mysql.yml
  roles:
     - { role: mysql }

- hosts: wordpress
  remote_user: ubuntu
  become: yes
  vars_files:
     - vars/Apache.yml
     - vars/Mysql.yml
  roles:
     - { role: wordpress }
