- hosts: web
  remote_user: user
  become: yes
  vars_files:
     - vars/Apache.yml
  roles:
    - apache
    - php
    - php-fpm

- hosts: db
  remote_user: user
  become: yes
  vars_files:
     - vars/Mysql.yml
  roles:
     - mysql 

- hosts: wordpress
  remote_user: user
  become: yes
  vars:
     pip_install_packages:
       - name: requests
  roles:
    - pip

- hosts: wordpress
  remote_user: user
  become: yes
  vars_files:
     - vars/Apache.yml
     - vars/Mysql.yml
     - vars/Wordpress.yml
  roles:
     - wordpress
