- hosts: web
  remote_user: ubuntu
  become: yes
  vars_files:
     - vars/Apache.yml
  roles:
    - apache
    - php
    - php-fpm

- hosts: db
  remote_user: ubuntu
  become: yes
  vars_files:
     - vars/Mysql.yml
  roles:
     - { role: mysql }

- hosts: wordpress
  remote_user: ubuntu
  become: yes
  vars_files:
     - vars/Apache.yml
     - vars/Mysql.yml
  roles:
     - { role: wordpress }
