
- name: Check if SElinux is installed
  stat:
    path: /bin/chcon
  register: is_selinux_exists

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
- name: Extract Wordpress 5.2.3.tgz
  unarchive:
    src: https://fr.wordpress.org/wordpress-5.2.3-fr_FR.tar.gz
    dest: "{{ item.website_folder }}"
    owner: "{{ pool_user }}"
    group: "{{ pool_group }}"
    remote_src: yes
  with_items: "{{ apache_vhosts }}"

- name: Allow SElinux (Wordpress rw)
  command: chcon -t httpd_sys_rw_content_t {{ wordpress_unarchived_path }} -R
  when: is_selinux_exists.stat.exists == True

- name: "Installation de Wordpress"
  wordpress_install:
    web_host: "{{ansible_host}}"
    db_name: "{{db_name}}"
    db_user: "{{db_user}}"
    db_pwd: "{{db_pwd}}"
    db_host: "{{db_host}}"
    site_name: "{{site_name}}"
    site_user: "{{site_user}}"
    site_pass: "{{site_pass}}"
  no_log: false
