---

- include_tasks: variables.yml

- name: Check Wordpress Unarchived
  stat:
    path: "{{ wordpress_unarchived_path }}"
  register: wordpress_unarchived

- include_tasks: install.yml
  when: wordpress_unarchived.stat.exists == false
